/**
 * YorStatus India — Database Seed
 * Run: node seed.js
 */
require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
process.chdir(require('path').join(__dirname, '..'));
const db = require('../db');

console.log('🌱 Seeding YorStatus database...');

/* ══════════════════════════════════════════════
   POLITICIANS
══════════════════════════════════════════════ */
const POLITICIANS = {
pm: [
 {name:"Narendra Modi",role:"Prime Minister of India",state:"Central",party:"BJP",twitter:"narendramodi",initials:"NM",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"Viksit Bharat 2047 — Developed Nation Roadmap",s:"prog",c:"Economy"},{t:"One Nation One Election implementation",s:"prog",c:"Governance"},{t:"3 crore homes under PM Awas Yojana 2.0",s:"prog",c:"Housing"},{t:"Uniform Civil Code national rollout",s:"pend",c:"Law"},{t:"2 crore jobs per year for Indian youth",s:"brok",c:"Employment"},{t:"Northeast — all state capitals rail-linked",s:"done",c:"Infrastructure"},{t:"Jan Dhan Yojana — banking for 52 crore",s:"done",c:"Finance"},{t:"Swachh Bharat — ODF India declared",s:"done",c:"Sanitation"},{t:"5G rollout across all 28 states",s:"done",c:"Technology"},{t:"₹15 lakh in every account (2014 promise)",s:"brok",c:"Economy"},{t:"Make India 3rd largest economy by 2027",s:"prog",c:"Economy"},{t:"PM Surya Ghar — 1 crore solar rooftops",s:"prog",c:"Energy"}]},
 {name:"Rajnath Singh",role:"Defence Minister",state:"Central",party:"BJP",twitter:"rajnathsingh",initials:"RS",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"Modernise armed forces with indigenous weapons",s:"prog",c:"Defence"},{t:"Agnipath military recruitment reform",s:"done",c:"Defence"},{t:"Defence exports target ₹50,000 crore",s:"prog",c:"Defence"},{t:"Self-reliant defence manufacturing Aatmanirbhar",s:"prog",c:"Defence"},{t:"DRDO budget doubled for R&D",s:"done",c:"Defence"}]},
 {name:"Amit Shah",role:"Home Affairs Minister",state:"Central",party:"BJP",twitter:"AmitShah",initials:"AS",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"NRC implementation across India",s:"pend",c:"Governance"},{t:"CAA fully implemented",s:"done",c:"Law"},{t:"Zero tolerance terrorism policy J&K",s:"prog",c:"Security"},{t:"Smart policing and crime data modernisation",s:"prog",c:"Governance"},{t:"One nation one police uniform",s:"pend",c:"Governance"},{t:"Operation Prahar — drug trafficking crackdown",s:"prog",c:"Security"}]},
 {name:"Nirmala Sitharaman",role:"Finance Minister",state:"Central",party:"BJP",twitter:"nsitharaman",initials:"NS",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"India become 3rd largest economy globally",s:"prog",c:"Economy"},{t:"Fiscal deficit below 4.5% GDP by 2026",s:"prog",c:"Finance"},{t:"New Direct Tax Code simplification",s:"prog",c:"Finance"},{t:"MSMEs credit guarantee expansion",s:"done",c:"Economy"},{t:"Digital Rupee (CBDC) rollout",s:"done",c:"Finance"},{t:"Abolish Angel Tax for startups",s:"done",c:"Economy"}]},
 {name:"S. Jaishankar",role:"External Affairs Minister",state:"Central",party:"BJP",twitter:"DrSJaishankar",initials:"SJ",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"India as voice of Global South",s:"prog",c:"Foreign Policy"},{t:"G20 presidency landmark achievements",s:"done",c:"Diplomacy"},{t:"Resolve China LAC border diplomatically",s:"prog",c:"Foreign Policy"},{t:"Diaspora welfare — passport reform",s:"prog",c:"Governance"},{t:"India in permanent UNSC seat bid",s:"prog",c:"Diplomacy"}]},
 {name:"Nitin Gadkari",role:"Road Transport & Highways",state:"Central",party:"BJP",twitter:"nitin_gadkari",initials:"NG",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"60,000 km national highways expansion",s:"prog",c:"Infrastructure"},{t:"Zero road accident deaths by 2030",s:"prog",c:"Safety"},{t:"EV charging on all national highways",s:"prog",c:"Environment"},{t:"Delhi-Mumbai Expressway operational",s:"done",c:"Infrastructure"},{t:"Har Shahar Har Gaon road connectivity",s:"prog",c:"Infrastructure"}]},
 {name:"JP Nadda",role:"Health & Family Welfare",state:"Central",party:"BJP",twitter:"JPNadda",initials:"JN",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"Ayushman Bharat — 70+ age free health cover",s:"done",c:"Health"},{t:"100 new medical colleges in 5 years",s:"prog",c:"Health"},{t:"Aatmanirbhar Pharma — domestic APIs",s:"prog",c:"Health"},{t:"Universal vaccination all children",s:"done",c:"Health"},{t:"Tele-medicine to all primary health centres",s:"prog",c:"Health"}]},
 {name:"Ashwini Vaishnaw",role:"Railways, Electronics & IT",state:"Central",party:"BJP",twitter:"AshwiniVaishnaw",initials:"AV",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"400 Vande Bharat trains across India",s:"prog",c:"Railways"},{t:"Zero railway accidents via Kavach system",s:"prog",c:"Safety"},{t:"Bullet train Mumbai–Ahmedabad corridor",s:"prog",c:"Railways"},{t:"100% railway electrification achieved",s:"done",c:"Railways"},{t:"Made-in-India semiconductor chips by 2026",s:"prog",c:"Technology"},{t:"AI-powered railway safety network",s:"prog",c:"Technology"}]},
 {name:"Dharmendra Pradhan",role:"Education Minister",state:"Central",party:"BJP",twitter:"dpradhanbjp",initials:"DP",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"NEP 2020 full rollout across all states",s:"prog",c:"Education"},{t:"Mother tongue medium in primary education",s:"prog",c:"Education"},{t:"PM SHRI — 14,500 upgraded model schools",s:"prog",c:"Education"},{t:"IIT and NIT expansion to all states",s:"prog",c:"Education"}]},
 {name:"Shivraj Singh Chouhan",role:"Agriculture & Farmers Welfare",state:"Central",party:"BJP",twitter:"ChouhanShivraj",initials:"SC",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"Double farmers income — extended to 2027",s:"prog",c:"Agriculture"},{t:"PM Kisan ₹6000/year to all farmers",s:"done",c:"Agriculture"},{t:"Natural farming zero-budget expansion",s:"prog",c:"Agriculture"},{t:"Soil health cards for every farmer",s:"done",c:"Agriculture"},{t:"Fasal Bima — better crop insurance",s:"prog",c:"Agriculture"}]},
 {name:"Jyotiraditya Scindia",role:"Telecom & NE Development",state:"Central",party:"BJP",twitter:"JM_Scindia",initials:"JS",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"BharatNet — broadband to every village",s:"prog",c:"Telecom"},{t:"5G in all district HQ by 2025",s:"prog",c:"Telecom"},{t:"Northeast as India drone hub by 2027",s:"pend",c:"Technology"}]},
 {name:"Manohar Lal",role:"Housing, Urban Affairs & Power",state:"Central",party:"BJP",twitter:"mlkhattar",initials:"ML",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"2 crore homes PMAY Urban 2.0",s:"prog",c:"Housing"},{t:"24/7 electricity all households",s:"done",c:"Power"},{t:"100 Smart Cities Mission completion",s:"prog",c:"Urban"}]},
 {name:"Hardeep Singh Puri",role:"Petroleum & Natural Gas",state:"Central",party:"BJP",twitter:"HardeepSPuri",initials:"HP",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"Ujjwala — 10 crore LPG households",s:"done",c:"Energy"},{t:"Reduce oil import dependency by 10%",s:"prog",c:"Energy"},{t:"CBG plants every district",s:"prog",c:"Energy"}]},
 {name:"Piyush Goyal",role:"Commerce & Industry",state:"Central",party:"BJP",twitter:"PiyushGoyal",initials:"PG",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"Exports target $1 trillion by 2030",s:"prog",c:"Trade"},{t:"FTAs with UK EU Canada finalised",s:"prog",c:"Trade"},{t:"Startup India — 1 lakh registered startups",s:"done",c:"Economy"},{t:"Ease of doing business — global top 50",s:"prog",c:"Governance"}]},
 {name:"Mansukh Mandaviya",role:"Labour, Employment & Sports",state:"Central",party:"BJP",twitter:"mansukhmandviya",initials:"MM",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"e-Shram — 28 crore workers registered",s:"done",c:"Labour"},{t:"India bid for Olympics 2036",s:"prog",c:"Sports"},{t:"EPFO and ESIC reforms for gig workers",s:"prog",c:"Labour"}]},
 {name:"G. Kishan Reddy",role:"Coal, Mines & Tourism",state:"Central",party:"BJP",twitter:"kishanreddybjp",initials:"GK",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"Coal production 1 billion tonnes",s:"prog",c:"Energy"},{t:"25 million foreign tourists by 2025",s:"prog",c:"Tourism"},{t:"50 Buddhist and heritage tourism circuits",s:"prog",c:"Tourism"}]},
 {name:"Kiren Rijiju",role:"Parliamentary & Minority Affairs",state:"Central",party:"BJP",twitter:"KirenRijiju",initials:"KR",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"Waqf Amendment Act implementation",s:"done",c:"Minority"},{t:"Productive Parliament sessions",s:"prog",c:"Governance"},{t:"Minority scholarship increase by 50%",s:"pend",c:"Education"}]},
 {name:"Chirag Paswan",role:"Food Processing Industries",state:"Central",party:"LJP(RV)",twitter:"iChiragPaswan",initials:"CP",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"PM SAMPADA — 2L crore food economy",s:"prog",c:"Agriculture"},{t:"One District One Food Product exports",s:"prog",c:"Economy"},{t:"Cold chain infrastructure every block",s:"prog",c:"Agriculture"}]},
 {name:"CR Patil",role:"Jal Shakti Minister",state:"Central",party:"BJP",twitter:"CRPaatil",initials:"CR",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"Jal Jeevan — tap water all households",s:"prog",c:"Water"},{t:"Namami Gange — clean Ganga by 2026",s:"prog",c:"Environment"},{t:"Atal Bhujal Yojana groundwater management",s:"prog",c:"Water"}]},
 {name:"Sarbananda Sonowal",role:"Ports, Shipping & Waterways",state:"Central",party:"BJP",twitter:"sarbanandsonwal",initials:"SS",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"Sagarmala port-led development",s:"prog",c:"Infrastructure"},{t:"Double waterway cargo by 2030",s:"prog",c:"Trade"},{t:"Inland water transport all major rivers",s:"prog",c:"Transport"}]},
 {name:"Annapurna Devi",role:"Women & Child Development",state:"Central",party:"BJP",twitter:"AnnapurnaDevi_7",initials:"AD",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"Mission Shakti — women safety and empowerment",s:"prog",c:"Women"},{t:"Poshan Abhiyaan — zero malnutrition",s:"prog",c:"Health"},{t:"Beti Bachao Beti Padhao all 640 districts",s:"done",c:"Women"}]},
 {name:"HD Kumaraswamy",role:"Heavy Industries & Steel",state:"Central",party:"JD(S)",twitter:"hd_kumaraswamy",initials:"HD",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"PLI scheme auto and heavy manufacturing",s:"prog",c:"Industry"},{t:"India steel export hub by 2030",s:"pend",c:"Industry"},{t:"EV manufacturing cluster development",s:"prog",c:"Technology"}]},
 {name:"Ram Mohan Naidu",role:"Civil Aviation Minister",state:"Central",party:"TDP",twitter:"RamMohanNaiduK",initials:"RN",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"UDAN — 100+ regional airports connected",s:"prog",c:"Aviation"},{t:"Greenfield airports Tier 2 and 3 cities",s:"prog",c:"Aviation"},{t:"India 3rd largest aviation market by 2030",s:"prog",c:"Aviation"}]},
 {name:"Prahlad Joshi",role:"New & Renewable Energy",state:"Central",party:"BJP",twitter:"JoshiPrahlad",initials:"PJ",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"500 GW renewable energy capacity by 2030",s:"prog",c:"Energy"},{t:"National Green Hydrogen Mission",s:"prog",c:"Energy"},{t:"PM Surya Ghar solar rooftops nationwide",s:"prog",c:"Energy"}]},
 {name:"Giriraj Singh",role:"Textiles Minister",state:"Central",party:"BJP",twitter:"girirajsinghbjp",initials:"GS",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"Textile exports 100 billion dollars by 2030",s:"prog",c:"Industry"},{t:"PM MITRA — 7 mega textile parks",s:"prog",c:"Industry"},{t:"MSME handloom weavers welfare",s:"prog",c:"Social"}]},
 {name:"Virendra Kumar",role:"Social Justice & Empowerment",state:"Central",party:"BJP",twitter:"virendrakumarmp",initials:"VK",ts:"2024-06-09",te:"2029-06-09",promises:[{t:"SC sub-categorisation in reservations",s:"prog",c:"Social"},{t:"PM Daksh skill dev for marginalised",s:"prog",c:"Employment"},{t:"Divyangjan welfare SIPDA expansion",s:"prog",c:"Social"}]},
],
cm:[
 {name:"N. Chandrababu Naidu",role:"Chief Minister",state:"Andhra Pradesh",party:"TDP",twitter:"ncbn",initials:"NC",ts:"2024-06-12",te:"2029-06-12",promises:[{t:"Polavaram dam complete by 2026",s:"prog",c:"Infrastructure"},{t:"Deepam — Rs 1000/month + LPG to every woman",s:"done",c:"Women"},{t:"Amaravati capital city rebuild",s:"prog",c:"Infrastructure"},{t:"Super Six welfare schemes",s:"prog",c:"Welfare"},{t:"Rs 15000 crore special package for AP",s:"prog",c:"Economy"},{t:"1 lakh govt jobs in 2 years",s:"prog",c:"Employment"}]},
 {name:"Pema Khandu",role:"Chief Minister",state:"Arunachal Pradesh",party:"BJP",twitter:"PemaKhanduBJP",initials:"PK",ts:"2016-07-17",te:"2031-07-17",promises:[{t:"All-weather connectivity border villages",s:"prog",c:"Infrastructure"},{t:"Arunachal ecotourism development",s:"prog",c:"Tourism"},{t:"Hydropower on all major rivers",s:"prog",c:"Energy"},{t:"Vibrant Village Programme implementation",s:"prog",c:"Security"}]},
 {name:"Himanta Biswa Sarma",role:"Chief Minister",state:"Assam",party:"BJP",twitter:"himantabiswa",initials:"HB",ts:"2021-05-10",te:"2026-05-10",promises:[{t:"Eviction of encroachments from govt land",s:"prog",c:"Governance"},{t:"Orunodoi 3.0 — Rs 1250/month to 23L families",s:"done",c:"Welfare"},{t:"Anti-drug campaign Nasha Mukt Assam",s:"prog",c:"Social"},{t:"NRC implementation in Assam",s:"prog",c:"Governance"},{t:"Flood-free Assam infrastructure by 2026",s:"pend",c:"Disaster"}]},
 {name:"Samrat Choudhary",role:"Chief Minister",state:"Bihar",party:"BJP",twitter:"SamratBJP4Bihar",initials:"SC",ts:"2026-04-15",te:"2031-04-15",promises:[{t:"1 lakh government jobs in first year",s:"pend",c:"Employment"},{t:"Prohibition law — alcohol ban maintained",s:"prog",c:"Social"},{t:"Illegal mining crackdown",s:"prog",c:"Governance"},{t:"Paper leak prevention — SIT formed",s:"done",c:"Education"},{t:"Abhay Brigade — women safety at public places",s:"done",c:"Safety"}]},
 {name:"Vishnu Deo Sai",role:"Chief Minister",state:"Chhattisgarh",party:"BJP",twitter:"vishnudsai",initials:"VD",ts:"2023-12-13",te:"2028-12-13",promises:[{t:"Ram Van Gaman Path tourism development",s:"prog",c:"Tourism"},{t:"PMAY homes for tribal families",s:"prog",c:"Housing"},{t:"Mahtari Vandan — Rs 1000/month to married women",s:"done",c:"Women"},{t:"Naxal-free Chhattisgarh by 2026",s:"prog",c:"Security"}]},
 {name:"Rekha Gupta",role:"Chief Minister",state:"Delhi",party:"BJP",twitter:"RekhaBJP4Delhi",initials:"RG",ts:"2025-02-20",te:"2030-02-20",promises:[{t:"Yamuna cleanup visible results by 2027",s:"prog",c:"Environment"},{t:"Delhi flood drainage overhaul",s:"prog",c:"Infrastructure"},{t:"1000 new electric buses for Delhi",s:"pend",c:"Transport"},{t:"Purvanchal freeway development",s:"pend",c:"Infrastructure"}]},
 {name:"Pramod Sawant",role:"Chief Minister",state:"Goa",party:"BJP",twitter:"DrPramodPSawant",initials:"PS",ts:"2019-03-19",te:"2027-03-19",promises:[{t:"Double Goa tourism revenue by 2025",s:"prog",c:"Tourism"},{t:"Casino revenue to social schemes",s:"prog",c:"Finance"},{t:"Goa linear transport network",s:"prog",c:"Transport"},{t:"Smart city for Panaji",s:"prog",c:"Urban"}]},
 {name:"Bhupendra Patel",role:"Chief Minister",state:"Gujarat",party:"BJP",twitter:"Bhupendrapbjp",initials:"BP",ts:"2021-09-13",te:"2027-12-01",promises:[{t:"Vibrant Gujarat — Rs 50L crore investment",s:"done",c:"Economy"},{t:"Narmada water to all arid districts",s:"prog",c:"Water"},{t:"Green hydrogen hub establishment",s:"prog",c:"Energy"},{t:"Saurashtra-Kutch connectivity",s:"prog",c:"Infrastructure"}]},
 {name:"Nayab Singh Saini",role:"Chief Minister",state:"Haryana",party:"BJP",twitter:"NayabSainiBJP",initials:"NS",ts:"2024-10-17",te:"2029-10-17",promises:[{t:"Monthly welfare scheme for women",s:"prog",c:"Women"},{t:"MSP for all Haryana crops",s:"prog",c:"Agriculture"},{t:"Zero drug abuse Haryana by 2027",s:"pend",c:"Social"},{t:"1 lakh govt jobs in 5 years",s:"pend",c:"Employment"}]},
 {name:"Sukhvinder Sukhu",role:"Chief Minister",state:"Himachal Pradesh",party:"INC",twitter:"SukhuSukhvinder",initials:"SS",ts:"2022-12-11",te:"2027-12-11",promises:[{t:"Old Pension Scheme fully restored",s:"done",c:"Finance"},{t:"IGPB — Rs 1500/month to women",s:"done",c:"Women"},{t:"125 units free electricity",s:"done",c:"Energy"},{t:"10L govt jobs for HP youth",s:"prog",c:"Employment"}]},
 {name:"Omar Abdullah",role:"Chief Minister",state:"Jammu & Kashmir",party:"NC",twitter:"OmarAbdullah",initials:"OA",ts:"2024-10-16",te:"2029-10-16",promises:[{t:"Restore full statehood for J&K",s:"prog",c:"Governance"},{t:"Domicile rights for all residents",s:"prog",c:"Rights"},{t:"Youth employment priority in govt",s:"prog",c:"Employment"},{t:"Lasting peace in Kashmir",s:"prog",c:"Security"}]},
 {name:"Hemant Soren",role:"Chief Minister",state:"Jharkhand",party:"JMM",twitter:"HemantSorenJMM",initials:"HS",ts:"2024-11-28",te:"2029-11-28",promises:[{t:"Maiyan Samman — Rs 2500/month to every woman",s:"done",c:"Women"},{t:"200 units free electricity per month",s:"done",c:"Energy"},{t:"Tribal land rights 1932 Khatiyan",s:"prog",c:"Rights"},{t:"Sarna religion code push",s:"prog",c:"Social"}]},
 {name:"Siddaramaiah",role:"Chief Minister",state:"Karnataka",party:"INC",twitter:"siddaramaiah",initials:"SI",ts:"2023-05-20",te:"2028-05-20",promises:[{t:"Shakti — free bus travel for all women",s:"done",c:"Transport"},{t:"Anna Bhagya — 10kg free rice BPL families",s:"done",c:"Welfare"},{t:"Gruha Jyoti — 200 units free electricity",s:"done",c:"Energy"},{t:"Gruha Lakshmi — Rs 2000/month women",s:"done",c:"Women"},{t:"Yuva Nidhi — Rs 3000/month unemployed graduates",s:"done",c:"Employment"},{t:"5 guarantees fully delivered",s:"done",c:"Welfare"}]},
 {name:"Pinarayi Vijayan",role:"Chief Minister",state:"Kerala",party:"CPI(M)",twitter:"vijayanpinarayi",initials:"PV",ts:"2021-05-20",te:"2026-05-20",promises:[{t:"K-Rail SilverLine semi-HSR project",s:"brok",c:"Transport"},{t:"LIFE Mission — homes for homeless",s:"done",c:"Housing"},{t:"100% school completion Kerala",s:"done",c:"Education"},{t:"Kerala IT exports Rs 1L crore target",s:"prog",c:"Economy"},{t:"Flood recovery 100% rehabilitation",s:"done",c:"Disaster"}]},
 {name:"Mohan Yadav",role:"Chief Minister",state:"Madhya Pradesh",party:"BJP",twitter:"DrMohanYadav51",initials:"MY",ts:"2023-12-13",te:"2028-12-13",promises:[{t:"Ladli Behna Yojana continued and enhanced",s:"done",c:"Women"},{t:"1 crore jobs in 5 years",s:"pend",c:"Employment"},{t:"Ujjain international spiritual tourism hub",s:"prog",c:"Tourism"},{t:"MP Rs 10L crore economy by 2028",s:"prog",c:"Economy"}]},
 {name:"Devendra Fadnavis",role:"Chief Minister",state:"Maharashtra",party:"BJP",twitter:"Dev_Fadnavis",initials:"DF",ts:"2024-12-05",te:"2029-12-05",promises:[{t:"Ladki Bahin — Rs 2100/month to women",s:"done",c:"Women"},{t:"Mumbai Metro Phase 3 Aqua Line",s:"prog",c:"Transport"},{t:"Vidarbha farmers debt relief",s:"prog",c:"Agriculture"},{t:"Zero slums Mumbai by 2030",s:"pend",c:"Housing"},{t:"Maharashtra Rs 1 trillion economy",s:"prog",c:"Economy"}]},
 {name:"Y. Khemchand Singh",role:"Chief Minister",state:"Manipur",party:"BJP",twitter:"YumnamKhemchand",initials:"YK",ts:"2026-03-30",te:"2031-03-30",promises:[{t:"Restore peace — ethnic conflict resolution",s:"prog",c:"Security"},{t:"Rehabilitation of displaced persons",s:"prog",c:"Welfare"},{t:"Rebuild ethnic harmony",s:"prog",c:"Social"}]},
 {name:"Conrad Sangma",role:"Chief Minister",state:"Meghalaya",party:"NPP",twitter:"SangmaConrad",initials:"CS",ts:"2018-03-06",te:"2028-03-06",promises:[{t:"1000-day transformation agenda",s:"prog",c:"Governance"},{t:"Meghalaya green tourism destination",s:"prog",c:"Tourism"},{t:"Coal mining ban compliance",s:"prog",c:"Environment"}]},
 {name:"Lalduhoma",role:"Chief Minister",state:"Mizoram",party:"ZPM",twitter:"lalduhoma",initials:"LD",ts:"2023-12-08",te:"2028-12-08",promises:[{t:"Drug-free Mizoram zero tolerance",s:"prog",c:"Social"},{t:"Transparent governance all contracts public",s:"prog",c:"Governance"},{t:"Myanmar refugee humanitarian support",s:"prog",c:"Welfare"}]},
 {name:"Neiphiu Rio",role:"Chief Minister",state:"Nagaland",party:"NDPP",twitter:"Neiphiu_Rio",initials:"NR",ts:"2018-03-08",te:"2028-03-08",promises:[{t:"Naga peace accord finalisation",s:"prog",c:"Governance"},{t:"Industrial policy for youth employment",s:"prog",c:"Employment"},{t:"Tourism and handloom exports",s:"prog",c:"Economy"}]},
 {name:"Mohan Charan Majhi",role:"Chief Minister",state:"Odisha",party:"BJP",twitter:"MohanMajhiOdisha",initials:"MM",ts:"2024-06-12",te:"2029-06-12",promises:[{t:"Subhadra Yojana — Rs 50000 to all women",s:"done",c:"Women"},{t:"Regularise 4L contractual employees",s:"prog",c:"Employment"},{t:"Mining revenue transparency",s:"prog",c:"Governance"},{t:"Odisha Sports Capital of India",s:"prog",c:"Sports"}]},
 {name:"Bhagwant Mann",role:"Chief Minister",state:"Punjab",party:"AAP",twitter:"BhagwantMann",initials:"BM",ts:"2022-03-16",te:"2027-03-16",promises:[{t:"1L govt jobs in 5 years",s:"prog",c:"Employment"},{t:"300 units free electricity per month",s:"done",c:"Energy"},{t:"AAP school model Punjab education",s:"prog",c:"Education"},{t:"Drug-free Punjab mission",s:"prog",c:"Social"},{t:"Mohalla clinics across Punjab",s:"prog",c:"Health"}]},
 {name:"N. Rangaswamy",role:"Chief Minister",state:"Puducherry",party:"AINRC",twitter:"NRangaswamy_CM",initials:"NR",ts:"2021-05-07",te:"2026-05-07",promises:[{t:"Statehood demand for Puducherry",s:"prog",c:"Governance"},{t:"Free sand scheme for construction",s:"done",c:"Housing"},{t:"Tourism revenue doubling by 2026",s:"prog",c:"Tourism"}]},
 {name:"Bhajanlal Sharma",role:"Chief Minister",state:"Rajasthan",party:"BJP",twitter:"BhajanlalBjp",initials:"BS",ts:"2023-12-15",te:"2028-12-15",promises:[{t:"Eastern Rajasthan Canal Project ERCP",s:"prog",c:"Water"},{t:"Lakhpati Didi women entrepreneurs",s:"prog",c:"Women"},{t:"100 units free electricity",s:"done",c:"Energy"},{t:"Rising Rajasthan Investment Summit",s:"done",c:"Economy"}]},
 {name:"Prem Singh Tamang",role:"Chief Minister",state:"Sikkim",party:"SKM",twitter:"PSTamangGolay",initials:"PT",ts:"2019-05-27",te:"2029-05-27",promises:[{t:"100% organic state certification",s:"done",c:"Agriculture"},{t:"Ecotourism hub development",s:"prog",c:"Tourism"},{t:"Earthquake preparedness infrastructure",s:"prog",c:"Disaster"}]},
 {name:"M.K. Stalin",role:"Chief Minister",state:"Tamil Nadu",party:"DMK",twitter:"mkstalin",initials:"MK",ts:"2021-05-07",te:"2026-05-07",promises:[{t:"10L jobs from new investments",s:"prog",c:"Employment"},{t:"Anti-NEET state medical admissions",s:"done",c:"Education"},{t:"Kalaignar Magalir Rs 1000/month to women",s:"done",c:"Women"},{t:"Tamil Nadu as EV hub",s:"prog",c:"Technology"},{t:"Dravidian model of governance",s:"prog",c:"Governance"}]},
 {name:"Revanth Reddy",role:"Chief Minister",state:"Telangana",party:"INC",twitter:"revanth_anumula",initials:"RR",ts:"2023-12-07",te:"2028-12-07",promises:[{t:"Rythu Bharosa — Rs 15000/year to farmers",s:"done",c:"Agriculture"},{t:"Gruha Jyoti — 200 units free electricity",s:"done",c:"Energy"},{t:"Indiramma Illu — 3L houses",s:"prog",c:"Housing"},{t:"Six guarantees full implementation",s:"prog",c:"Welfare"},{t:"Hyderabad Future City megaproject",s:"prog",c:"Urban"}]},
 {name:"Manik Saha",role:"Chief Minister",state:"Tripura",party:"BJP",twitter:"DrManikSaha2",initials:"MS",ts:"2022-05-15",te:"2028-05-15",promises:[{t:"Smart city development Agartala",s:"prog",c:"Urban"},{t:"Industrial park reduce unemployment",s:"prog",c:"Employment"},{t:"Natural gas pipeline all districts",s:"prog",c:"Energy"},{t:"NE India gateway to Southeast Asia",s:"prog",c:"Economy"}]},
 {name:"Pushkar Singh Dhami",role:"Chief Minister",state:"Uttarakhand",party:"BJP",twitter:"pushkardhami",initials:"PD",ts:"2022-03-23",te:"2027-03-23",promises:[{t:"UCC — India first state implementation",s:"done",c:"Law"},{t:"Gangotri-Yamunotri spiritual corridor",s:"prog",c:"Tourism"},{t:"Anti-copying law fair exams",s:"done",c:"Education"},{t:"Char Dham all-weather road",s:"prog",c:"Infrastructure"}]},
 {name:"Yogi Adityanath",role:"Chief Minister",state:"Uttar Pradesh",party:"BJP",twitter:"myogiadityanath",initials:"YA",ts:"2017-03-19",te:"2027-03-19",promises:[{t:"Ram Temple consecration completed",s:"done",c:"Religion"},{t:"Bulldozer action anti-encroachment",s:"prog",c:"Security"},{t:"UP 6 major expressways network",s:"done",c:"Infrastructure"},{t:"Invest UP Rs 40L crore summit",s:"prog",c:"Economy"},{t:"1 crore jobs in 5 years",s:"prog",c:"Employment"},{t:"UP 1 trillion dollar economy by 2027",s:"prog",c:"Economy"}]},
 {name:"Mamata Banerjee",role:"Chief Minister",state:"West Bengal",party:"TMC",twitter:"MamataOfficial",initials:"MB",ts:"2011-05-20",te:"2026-05-20",promises:[{t:"Lakshmir Bhandar — Rs 1000/month to women",s:"done",c:"Women"},{t:"Duare Sarkar — govt services at doorstep",s:"done",c:"Governance"},{t:"Kanyashree education support for girls",s:"done",c:"Education"},{t:"Silicon Valley East — Bengal IT hub",s:"prog",c:"Economy"},{t:"Sabuj Sathi cycles to every student",s:"done",c:"Education"}]},
],
opp:[
 {name:"Rahul Gandhi",role:"Leader of Opposition, Lok Sabha",state:"INC",party:"INC",twitter:"RahulGandhi",initials:"RG",ts:"2024-06-24",te:"2029-06-24",promises:[{t:"25% OBC reservation in private sector",s:"pend",c:"Social"},{t:"Nationwide caste census and data release",s:"prog",c:"Governance"},{t:"Mahalaxmi — Rs 1L/year to poorest women",s:"pend",c:"Women"},{t:"Legal right to apprenticeship",s:"pend",c:"Employment"},{t:"Oppose and reform NEET system",s:"prog",c:"Education"},{t:"Bharat Jodo Yatra national unity",s:"done",c:"Politics"}]},
 {name:"Mallikarjun Kharge",role:"INC President & Rajya Sabha LOP",state:"INC",party:"INC",twitter:"kharge",initials:"MK",ts:"2022-10-26",te:"2027-10-26",promises:[{t:"INDIA alliance consolidation",s:"prog",c:"Politics"},{t:"Constitution protection campaign",s:"prog",c:"Rights"},{t:"Dalit SC-ST welfare push",s:"prog",c:"Social"}]},
 {name:"Arvind Kejriwal",role:"AAP National Convenor",state:"AAP",party:"AAP",twitter:"ArvindKejriwal",initials:"AK",ts:"2024-03-21",te:"2029-03-21",promises:[{t:"AAP government in major states",s:"prog",c:"Politics"},{t:"Free electricity model replicated nationally",s:"prog",c:"Energy"},{t:"Mohalla clinic model across all states",s:"prog",c:"Health"},{t:"Education revolution AAP school model",s:"prog",c:"Education"}]},
 {name:"Akhilesh Yadav",role:"SP President & LOP UP Assembly",state:"UP",party:"SP",twitter:"yadavakhilesh",initials:"AY",ts:"2022-03-10",te:"2027-03-10",promises:[{t:"PDA coalition Pichda Dalit Alpasankhyak",s:"prog",c:"Politics"},{t:"Restore 84L youth domicile jobs",s:"pend",c:"Employment"},{t:"Free laptop to every UP graduate",s:"pend",c:"Education"}]},
 {name:"Tejashwi Yadav",role:"RJD President & LOP Bihar",state:"Bihar",party:"RJD",twitter:"yadavtejashwi",initials:"TY",ts:"2022-08-10",te:"2027-08-10",promises:[{t:"10L government jobs for Bihar",s:"prog",c:"Employment"},{t:"Social justice for OBC SC ST",s:"prog",c:"Social"},{t:"Young leadership for Bihar",s:"prog",c:"Governance"}]},
 {name:"Sharad Pawar",role:"NCP(SP) President",state:"Maharashtra",party:"NCP(SP)",twitter:"PawarSpeaks",initials:"SP",ts:"2023-07-02",te:"2028-07-02",promises:[{t:"MVA alliance INC SS UBT NCP",s:"prog",c:"Politics"},{t:"Farmers rights and legal MSP guarantee",s:"prog",c:"Agriculture"},{t:"Counter authoritarian governance",s:"prog",c:"Governance"}]},
 {name:"Uddhav Thackeray",role:"Shiv Sena UBT President",state:"Maharashtra",party:"SS(UBT)",twitter:"OfficeofUT",initials:"UT",ts:"2022-06-30",te:"2027-06-30",promises:[{t:"Marathi manoos first local employment",s:"prog",c:"Employment"},{t:"True Hindutva position",s:"prog",c:"Politics"},{t:"Restore democratic legitimacy Maharashtra",s:"prog",c:"Governance"}]},
 {name:"Sitaram Yechury",role:"CPI(M) General Secretary",state:"CPI(M)",party:"CPI(M)",twitter:"SitaramYechury",initials:"SY",ts:"2015-04-20",te:"2030-04-20",promises:[{t:"Left unity for opposition front",s:"prog",c:"Politics"},{t:"Workers and farmers constitutional rights",s:"prog",c:"Social"},{t:"Oppose corporate-govt nexus",s:"prog",c:"Governance"}]},
]};

const PARTIES=[
 {slug:"bjp",name:"BJP",full:"Bharatiya Janata Party",color:"#FF6B00",founded:1980,ideology:"Hindu nationalism · Developmental politics · Right-wing populism",seats2024:240,states:JSON.stringify(["UP","Gujarat","MP","Rajasthan","Maharashtra","CG","Assam","Uttarakhand","Tripura","Goa","Bihar","Manipur","Odisha","Haryana","Delhi"]),prev:{year:2019,title:"Sankalp Patra 2019 — Modi Ki Guarantee",promises:[{t:"Abrogation of Article 370 in J&K",s:"done",impact:"J&K became UT. Tourism revived 400%. Political autonomy removed."},{t:"Ram Mandir construction in Ayodhya",s:"done",impact:"Temple consecrated Jan 2024. Tourism surged. Rs 40,000 crore development."},{t:"Citizenship Amendment Act CAA passed",s:"done",impact:"Implemented 2024. Persecuted minority refugees aided. Domestic protests."},{t:"Nationwide NRC implementation",s:"pend",impact:"Not implemented nationally. Legal and logistical barriers persist."},{t:"Double farmers income by 2022",s:"brok",impact:"Income not doubled. Farm laws repealed 2021 after massive protests."},{t:"Swachh Bharat ODF India",s:"done",impact:"10+ crore toilets built. Open defecation declared eliminated."},{t:"Digital India UPI payment revolution",s:"done",impact:"UPI: world's largest real-time payment system. 100B+ monthly transactions."},{t:"Make in India manufacturing hub",s:"prog",impact:"PLI success in mobiles and defence. Share below 25% GDP target."}]},curr:{year:2024,title:"Modi Ki Guarantee 2024",promises:[{t:"Viksit Bharat 2047 Developed Nation",s:"prog",impact:"Vision document released. Implementation framework set."},{t:"One Nation One Election",s:"prog",impact:"JPC formed, bill drafted. Constitutional amendments required."},{t:"Uniform Civil Code national rollout",s:"pend",impact:"Uttarakhand first. National implementation pending."},{t:"3 crore new homes PMAY 2.0",s:"prog",impact:"Rs 10L crore scheme approved. Ongoing."},{t:"India GDP to 5 trillion by 2027",s:"prog",impact:"Currently ~3.7T. Tight timeline."}]}},
 {slug:"inc",name:"INC",full:"Indian National Congress",color:"#00C851",founded:1885,ideology:"Social democracy · Secularism · Centrism",seats2024:99,states:JSON.stringify(["Karnataka","Himachal Pradesh","Telangana"]),prev:{year:2019,title:"Congress Manifesto 2019 — Hum Nibhayenge",promises:[{t:"NYAY scheme Rs 72000/year to 5 crore families",s:"brok",impact:"Lost election. Never implemented. Would cost Rs 3.6L crore/year."},{t:"22 lakh government jobs guarantee",s:"brok",impact:"Not in power at centre. Not implemented."},{t:"GST simplification single slab",s:"brok",impact:"Not implemented. In opposition."},{t:"6% GDP on education spending",s:"brok",impact:"India at ~4.6% GDP on education."},{t:"Farm loan waiver 3-year interest-free",s:"brok",impact:"Not nationally. INC states Karnataka Telangana implemented partial."}]},curr:{year:2024,title:"25 Guarantees Nyay Patra 2024",promises:[{t:"Caste census OBC data public release",s:"prog",impact:"Bihar did state census. National push underway."},{t:"25% OBC reservation in private sector",s:"pend",impact:"Constitutional amendment required. In opposition."},{t:"Mahalaxmi Rs 1L/year poorest women",s:"pend",impact:"Not in power at centre."},{t:"Legal MSP guarantee for farmers",s:"pend",impact:"Farmers demanded since 2021 protests."},{t:"Apprenticeship right 1 crore youth",s:"pend",impact:"Proposed legislation not passed."}]}},
 {slug:"aap",name:"AAP",full:"Aam Aadmi Party",color:"#3B82F6",founded:2012,ideology:"Anti-corruption · Direct democracy · Populism",seats2024:3,states:JSON.stringify(["Punjab"]),prev:{year:2020,title:"Delhi Manifesto 2020 — Real Delhi Model",promises:[{t:"Free electricity 200 units per household",s:"done",impact:"47L households benefit. Rs 3500 crore/year subsidy."},{t:"Free water 20000 litres/month per family",s:"done",impact:"25L+ connections benefit."},{t:"1000 Mohalla Clinics across Delhi",s:"done",impact:"970+ clinics. WHO studied as model."},{t:"World-class Delhi government schools",s:"done",impact:"Board results improved. International attention."},{t:"Clean Yamuna river by 2025",s:"brok",impact:"River remains heavily polluted. Rs 6000+ crore spent. Target missed."},{t:"Zero corruption in Delhi government",s:"brok",impact:"Kejriwal and multiple AAP leaders arrested in liquor policy case."},{t:"10 lakh jobs for Delhi youth",s:"brok",impact:"No significant job creation demonstrated."}]},curr:{year:2025,title:"AAP 2025 Punjab Manifesto",promises:[{t:"Expand 300 units free electricity Punjab",s:"done",impact:"Implemented in Punjab since 2022."},{t:"Mohalla clinics in every block of Punjab",s:"prog",impact:"Rollout ongoing."},{t:"1L govt jobs in 5-year term",s:"prog",impact:"Recruitment ongoing ~35000 done."},{t:"Drug-free Punjab by 2027",s:"prog",impact:"Anti-narco drive active."}]}},
 {slug:"tmc",name:"TMC",full:"All India Trinamool Congress",color:"#06B6D4",founded:1998,ideology:"Left-wing populism · Bengali sub-nationalism · Secularism",seats2024:29,states:JSON.stringify(["West Bengal"]),prev:{year:2021,title:"TMC WB 2021 — Banglar Gorbo Mamata",promises:[{t:"Lakshmir Bhandar Rs 500-1000/month to women",s:"done",impact:"1.6 crore beneficiaries. Credited with TMC win."},{t:"Duare Sarkar government at doorstep camps",s:"done",impact:"19 crore+ services delivered across 12000+ camps."},{t:"Swasthya Sathi free Rs 5L health insurance",s:"done",impact:"7.8 crore+ beneficiaries enrolled."},{t:"Sabuj Sathi free cycles for students",s:"done",impact:"1.1 crore+ cycles. Girls dropout rate reduced."},{t:"Silicon Valley East IT investment in WB",s:"prog",impact:"Some IT investment. Kolkata tech growing but gap with Bengaluru massive."},{t:"Zero unemployment in West Bengal",s:"brok",impact:"High youth unemployment persists. Significant outmigration."}]},curr:{year:2026,title:"TMC WB 2026 Manifesto",promises:[{t:"Increase Lakshmir Bhandar to Rs 2000/month",s:"pend",impact:"Pre-election announcement."},{t:"WB GDP double by 2029",s:"pend",impact:"Ambitious target."},{t:"Kanyashree expansion all girls till graduation",s:"prog",impact:"Being expanded."}]}},
 {slug:"dmk",name:"DMK",full:"Dravida Munnetra Kazhagam",color:"#EF4444",founded:1949,ideology:"Dravidian movement · Social justice · Federalism",seats2024:22,states:JSON.stringify(["Tamil Nadu"]),prev:{year:2021,title:"DMK TN 2021 — Ungal Aatchi Ungal Ooril",promises:[{t:"Rs 1000/month to women heads of household",s:"done",impact:"Kalaignar Magalir Urimai. 1.06 crore women."},{t:"Anti-NEET fight state-level medical admissions",s:"done",impact:"State law passed. Legal battle with Centre ongoing."},{t:"10 lakh government jobs in 5 years",s:"prog",impact:"~3L jobs provided. Ongoing."},{t:"Farm loan waiver cooperative banks",s:"done",impact:"Rs 12110 crore waived. 3.66 lakh farmers."},{t:"Liquor prohibition step-by-step",s:"brok",impact:"No prohibition. TASMAC revenue critical."},{t:"Tamil Nadu EV hub by 2025",s:"prog",impact:"Ola Ather Hyundai Tata EV plants established."}]},curr:{year:2026,title:"DMK TN 2026 Manifesto",promises:[{t:"Rs 2000/month to all women Kalaignar enhanced",s:"pend",impact:"Pre-election promise."},{t:"Complete NEET abolition in TN",s:"prog",impact:"Legal battle ongoing."},{t:"TN 1 trillion dollar economy by 2030",s:"prog",impact:"Currently 3rd largest state economy."}]}},
 {slug:"sp",name:"SP",full:"Samajwadi Party",color:"#F87171",founded:1992,ideology:"Socialism · Social justice · OBC-Muslim coalition",seats2024:37,states:JSON.stringify([]),prev:{year:2022,title:"SP UP 2022 Manifesto",promises:[{t:"Smartphones tablets to all students",s:"brok",impact:"Lost election. Not implemented."},{t:"200 units free electricity in UP",s:"brok",impact:"Lost election."},{t:"PDA coalition social justice governance",s:"prog",impact:"Built as opposition. Strong 2024 Lok Sabha showing."},{t:"Restore cancelled reservations",s:"pend",impact:"In opposition."}]},curr:{year:2027,title:"SP UP 2027 Vision",promises:[{t:"PDA model OBC-Dalit-Minority coalition",s:"prog",impact:"Building for 2027 state elections."},{t:"Legal MSP guarantee in UP",s:"pend",impact:"Proposed."},{t:"Free laptops to graduates",s:"pend",impact:"Re-announced."}]}},
 {slug:"jmm",name:"JMM",full:"Jharkhand Mukti Morcha",color:"#4ADE80",founded:1972,ideology:"Tribal rights · Regional autonomy · Leftism",seats2024:3,states:JSON.stringify(["Jharkhand"]),prev:{year:2019,title:"JMM-INC Alliance 2019",promises:[{t:"Tribal land rights 1932 Khatiyan domicile",s:"prog",impact:"Partially implemented. Legal challenge continues."},{t:"Maiyan Samman monthly cash to women",s:"done",impact:"Rs 2500/month. 57 lakh women. Credited with 2024 win."},{t:"Old Pension Scheme restoration",s:"done",impact:"Implemented. Popular but fiscally contested."},{t:"Free rice pulses to poor families",s:"done",impact:"Universal food security expanded."},{t:"Anti-mining mafia action",s:"prog",impact:"Some arrests. Illegal mining persists."}]},curr:{year:2024,title:"JMM 2024 Election Guarantee",promises:[{t:"Increase Maiyan Samman to Rs 3500/month",s:"pend",impact:"Post-election implementation pending."},{t:"1932 Khatiyan domicile full implementation",s:"prog",impact:"Legal battle ongoing."},{t:"100 units free electricity",s:"prog",impact:"Being rolled out."}]}},
 {slug:"cpim",name:"CPI(M)",full:"Communist Party of India Marxist",color:"#DC2626",founded:1964,ideology:"Marxism-Leninism · Democratic socialism · Secularism",seats2024:4,states:JSON.stringify(["Kerala"]),prev:{year:2021,title:"LDF Kerala 2021 — Kerala Model Forward",promises:[{t:"Rebuild Kerala economy post-COVID",s:"done",impact:"Kerala recovered strongly. IT and remittance grew."},{t:"LIFE Mission homes to all homeless families",s:"done",impact:"4.25 lakh homes. WHO model."},{t:"100% school enrollment and completion rate",s:"done",impact:"Near-perfect literacy and completion."},{t:"K-Rail SilverLine semi-HSR project",s:"brok",impact:"Rs 65000 crore cancelled after public opposition."},{t:"Kerala IT exports Rs 1L crore target",s:"prog",impact:"At Rs 70000+ crore. Growing fast."},{t:"Free ration to all BPL families",s:"done",impact:"Expanded food security. Universal coverage."}]},curr:{year:2026,title:"LDF Kerala 2026",promises:[{t:"Kerala Fibernet broadband to every home",s:"prog",impact:"KFon project ongoing. 20L connections planned."},{t:"Public transport revolution e-buses",s:"prog",impact:"KSRTC electrification underway."},{t:"Attract Rs 2L crore investment in Kerala",s:"pend",impact:"Investment summits planned."}]}}
];

const STATES=[
 {name:"Telangana",cm:"Revanth Reddy",party:"INC",gdp:13.8,size:"14.5",hdi:0.669,lit:72.8,unemp:4.2,si:78,sw:82,se:85,sg:72,sn:55,decisions:[{t:"Rythu Bharosa Rs 15000/year to farmers",type:"pos",impact:"1.5 crore farmers benefited. Reduced farmer distress."},{t:"Free electricity 200 units all homes",type:"pos",impact:"2.8 crore consumers. Large fiscal commitment."},{t:"Hyderabad Future City megaproject",type:"mix",impact:"5L+ jobs expected but displacement concerns."},{t:"TSIPARD data centres IT policy",type:"pos",impact:"Hyderabad 2nd largest IT hub. 8L+ tech jobs."}]},
 {name:"Gujarat",cm:"Bhupendra Patel",party:"BJP",gdp:12.4,size:"21.5",hdi:0.672,lit:78.0,unemp:2.5,si:88,sw:65,se:90,sg:80,sn:50,decisions:[{t:"Vibrant Gujarat Summits Rs 50L crore investments",type:"pos",impact:"Semiconductor EV defence investments. 10L+ jobs."},{t:"GIFT City global IFSC hub",type:"pos",impact:"India only IFSC. 20000+ jobs. 50B+ assets."},{t:"Narmada water distribution",type:"mix",impact:"Irrigation to arid regions. Displacement controversially managed."},{t:"Anti-encroachment tribal areas",type:"neg",impact:"Forcible evictions documented. Human rights concerns."}]},
 {name:"Karnataka",cm:"Siddaramaiah",party:"INC",gdp:11.2,size:"21.0",hdi:0.682,lit:75.6,unemp:3.8,si:80,sw:88,se:84,sg:76,sn:65,decisions:[{t:"5 Guarantees Rs 52000 crore/year to poor",type:"pos",impact:"Direct cash to 1.4 crore women. Free rice electricity."},{t:"Bengaluru infrastructure investment",type:"mix",impact:"Metro expanding. But flooding and traffic still severe."},{t:"Mysuru-Bengaluru Expressway completed",type:"pos",impact:"Travel time halved. Economic corridor activated."},{t:"State debt rising under guarantees",type:"neg",impact:"Debt Rs 4.6L crore. Credit watch. Fiscal sustainability debated."}]},
 {name:"Maharashtra",cm:"Devendra Fadnavis",party:"BJP",gdp:10.1,size:"35.2",hdi:0.696,lit:82.3,unemp:3.5,si:82,sw:74,se:88,sg:70,sn:55,decisions:[{t:"Mumbai Coastal Road Metro expansion",type:"pos",impact:"20L daily passengers when complete."},{t:"Ladki Bahin Rs 2100/month to women",type:"pos",impact:"2.4 crore women. Credited with 2024 win."},{t:"Dharavi Redevelopment project",type:"mix",impact:"Rs 20000 crore. Rehab concerns for 6.5L residents."},{t:"Farmer suicides Vidarbha crisis",type:"neg",impact:"2000+ annual deaths. Distress persists."}]},
 {name:"Andhra Pradesh",cm:"N. Chandrababu Naidu",party:"TDP",gdp:9.8,size:"13.2",hdi:0.650,lit:67.0,unemp:5.1,si:75,sw:72,se:76,sg:74,sn:60,decisions:[{t:"Amaravati capital city restart",type:"mix",impact:"Rs 67000 crore restarted. Timeline uncertain."},{t:"Deepam LPG cash to women",type:"pos",impact:"2 crore+ women benefited."},{t:"AP Industrial Policy 2023-27",type:"pos",impact:"Rs 2L crore investment target."},{t:"4 years YSRCP policy reversal costs",type:"neg",impact:"Policy instability cost investors."}]},
 {name:"Tamil Nadu",cm:"M.K. Stalin",party:"DMK",gdp:9.2,size:"23.5",hdi:0.708,lit:80.1,unemp:4.0,si:78,sw:80,se:82,sg:78,sn:62,decisions:[{t:"Kalaignar Magalir Rs 1000/month to women",type:"pos",impact:"1.06 crore women. Rs 7000 crore/year."},{t:"Anti-NEET legislation TN",type:"pos",impact:"Local students in medical colleges increased."},{t:"TN EV policy manufacturer incentives",type:"pos",impact:"50000+ jobs created."},{t:"Sterlite copper plant closure",type:"neg",impact:"Copper shortage nationally. 13 protesters died in 2018."}]},
 {name:"Rajasthan",cm:"Bhajanlal Sharma",party:"BJP",gdp:8.9,size:"11.8",hdi:0.629,lit:66.1,unemp:5.5,si:70,sw:68,se:72,sg:68,sn:58,decisions:[{t:"Rising Rajasthan Summit Rs 12L crore pledges",type:"pos",impact:"Solar tourism mining investment."},{t:"ERCP Eastern Rajasthan Canal Project",type:"pos",impact:"Water to 13 drought-prone districts."},{t:"Cancelled Gehlot urban employment scheme",type:"neg",impact:"Poor urban workers lost income."},{t:"Paper leaks RAS teacher recruitment",type:"neg",impact:"Exam credibility crisis."}]},
 {name:"Madhya Pradesh",cm:"Mohan Yadav",party:"BJP",gdp:8.4,size:"10.2",hdi:0.606,lit:69.3,unemp:5.8,si:68,sw:72,se:70,sg:65,sn:68,decisions:[{t:"Ladli Behna Yojana Rs 1250/month continued",type:"pos",impact:"1.25 crore women. Template for other states."},{t:"MP Industry Policy 2023 new investments",type:"pos",impact:"EV food pharma sectors attracting investment."},{t:"Sand mining mafia illegal operations",type:"neg",impact:"River exploitation rampant. Political links alleged."},{t:"Farmer loan waivers delayed partial",type:"neg",impact:"Many farmers still heavily indebted."}]},
 {name:"Uttar Pradesh",cm:"Yogi Adityanath",party:"BJP",gdp:7.8,size:"17.2",hdi:0.596,lit:67.7,unemp:6.2,si:75,sw:62,se:72,sg:68,sn:45,decisions:[{t:"Six expressways UP infrastructure revolution",type:"pos",impact:"4000+ km. Industrial investment followed."},{t:"Ayodhya Ram Circuit development",type:"pos",impact:"Tourism surged 1000%+. Rs 40000 crore investment."},{t:"Bulldozer action criminal properties",type:"mix",impact:"Deterrent effect but SC intervened with guidelines."},{t:"COVID migrant labourers poor handling",type:"neg",impact:"Millions walked home. Policy failure."}]},
 {name:"Odisha",cm:"Mohan Charan Majhi",party:"BJP",gdp:7.9,size:"7.5",hdi:0.606,lit:72.9,unemp:4.8,si:72,sw:75,se:74,sg:76,sn:70,decisions:[{t:"Subhadra Yojana Rs 50000 to all women",type:"pos",impact:"1.3 crore+ women enrolled."},{t:"Mining revenue transparency reforms",type:"pos",impact:"Better royalty collection."},{t:"Odisha Hockey World Cup hosting",type:"pos",impact:"Global recognition. Infrastructure built."},{t:"Cyclone Fani recovery management",type:"pos",impact:"Zero evacuation deaths. Praised by UN."}]},
 {name:"West Bengal",cm:"Mamata Banerjee",party:"TMC",gdp:6.8,size:"14.6",hdi:0.641,lit:77.1,unemp:5.2,si:65,sw:80,se:62,sg:55,sn:60,decisions:[{t:"Duare Sarkar 19 crore services delivered",type:"pos",impact:"Largest doorstep delivery programme."},{t:"Lakshmir Bhandar Rs 1000/month",type:"pos",impact:"1.63 crore women consistent delivery."},{t:"Post-election political violence 2021",type:"neg",impact:"200+ deaths. NHRC found rule of law failures."},{t:"Sandeshkhali exploitation scandal",type:"neg",impact:"Women exploitation by TMC leaders. 2024."}]},
 {name:"Kerala",cm:"Pinarayi Vijayan",party:"CPI(M)",gdp:6.2,size:"9.8",hdi:0.779,lit:94.0,unemp:6.8,si:72,sw:88,se:70,sg:80,sn:78,decisions:[{t:"LIFE Mission 4.25 lakh homes for homeless",type:"pos",impact:"Zero homelessness targeted. WHO model."},{t:"K-SilverLine railway cancelled",type:"neg",impact:"Rs 65000 crore cancelled. Opportunity lost."},{t:"KSEB renewable energy 80pct RE",type:"pos",impact:"Near energy-independent. EV penetration highest."},{t:"State fiscal crisis debt 3.3L crore",type:"neg",impact:"Centre restricting borrowing. Salary delays."}]},
 {name:"Jharkhand",cm:"Hemant Soren",party:"JMM",gdp:6.0,size:"4.4",hdi:0.599,lit:66.4,unemp:6.5,si:60,sw:74,se:62,sg:64,sn:65,decisions:[{t:"Maiyan Samman Rs 2500/month 57L women",type:"pos",impact:"Largest women income scheme. Election game-changer."},{t:"1932 Khatiyan domicile policy",type:"mix",impact:"Tribal rights protected. Legal battle continues."},{t:"Coal mining regulation improvements",type:"mix",impact:"Royalty collection improved. Illegal mining persists."}]},
 {name:"Assam",cm:"Himanta Biswa Sarma",party:"BJP",gdp:6.5,size:"4.5",hdi:0.614,lit:72.2,unemp:5.8,si:68,sw:65,se:64,sg:70,sn:60,decisions:[{t:"Orunodoi 3.0 Rs 1250/month to 23L families",type:"pos",impact:"Direct benefit delivery improved."},{t:"Darrang district evictions 2021",type:"neg",impact:"2 deaths. Human rights concerns documented."},{t:"NRC 19L excluded detention centres",type:"neg",impact:"Lives disrupted. SC monitoring."}]},
 {name:"Punjab",cm:"Bhagwant Mann",party:"AAP",gdp:5.8,size:"7.5",hdi:0.695,lit:75.8,unemp:7.5,si:62,sw:72,se:58,sg:70,sn:55,decisions:[{t:"300 units free electricity 2.7 crore households",type:"pos",impact:"Rs 1800 crore/year subsidy. Households relieved."},{t:"AAP school transformation Rs 15000 crore",type:"pos",impact:"Results improved. Infrastructure upgraded."},{t:"Anti-drug Mohalla Clinics 2022-25",type:"pos",impact:"OPD burden reducing."},{t:"State debt Rs 3.3L crore free scheme strain",type:"neg",impact:"Punjab fiscal crisis serious."}]},
 {name:"Himachal Pradesh",cm:"Sukhvinder Sukhu",party:"INC",gdp:7.2,size:"2.0",hdi:0.725,lit:82.8,unemp:7.8,si:70,sw:75,se:60,sg:68,sn:80,decisions:[{t:"Old Pension Scheme restored for 1.25L employees",type:"pos",impact:"Employees protected. Rs 800 crore/year fiscal burden."},{t:"IGPB Rs 1500/month to 2.7L women",type:"pos",impact:"Delivered consistently."},{t:"Shimla and Kullu floods 2023",type:"neg",impact:"50+ deaths. Rs 8000 crore damage."},{t:"Apple farmers market access problems",type:"mix",impact:"Some support. Middlemen still dominate."}]},
 {name:"Delhi",cm:"Rekha Gupta",party:"BJP",gdp:8.5,size:"9.6",hdi:0.746,lit:86.2,unemp:4.0,si:75,sw:65,se:82,sg:68,sn:35,decisions:[{t:"Metro Phase 4 expansion 65+ km new lines",type:"pos",impact:"NCR connectivity improving."},{t:"Free electricity slab structure retained",type:"mix",impact:"Popular scheme maintained."},{t:"Annual AQI emergency worlds worst city",type:"neg",impact:"Health emergency every winter."},{t:"Yamuna dead zone continued failure",type:"neg",impact:"Rs 20000 crore spent. River remains polluted."}]},
 {name:"Bihar",cm:"Samrat Choudhary",party:"BJP",gdp:5.5,size:"6.1",hdi:0.574,lit:61.8,unemp:6.5,si:55,sw:60,se:50,sg:58,sn:62,decisions:[{t:"Prohibition alcohol ban since 2016",type:"mix",impact:"Domestic violence improved. Bootlegging thrives. Rs 5000 crore loss/year."},{t:"Saat Nischay village-level infrastructure",type:"pos",impact:"Electrification roads drains to all villages."},{t:"Annual devastating floods poor mitigation",type:"neg",impact:"15M+ displaced annually. Long-term investment lacking."},{t:"Industrial absence youth outmigration",type:"neg",impact:"Bihar GDP growth below potential."}]},
 {name:"Uttarakhand",cm:"Pushkar Singh Dhami",party:"BJP",gdp:8.1,size:"2.9",hdi:0.684,lit:78.8,unemp:4.5,si:72,sw:68,se:70,sg:74,sn:72,decisions:[{t:"UCC Uniform Civil Code first state",type:"pos",impact:"Historic. Template nationally."},{t:"Char Dham all-weather road Himalayas",type:"mix",impact:"Connectivity improved. Ecological damage documented."},{t:"Silkyara tunnel rescue 41 workers saved",type:"pos",impact:"Global praise."},{t:"Joshimath land subsidence crisis",type:"neg",impact:"800+ structures cracked. 4000+ families at risk."}]},
 {name:"Haryana",cm:"Nayab Singh Saini",party:"BJP",gdp:7.0,size:"8.7",hdi:0.708,lit:75.6,unemp:5.8,si:74,sw:65,se:75,sg:68,sn:50,decisions:[{t:"Haryana 75pct local reservation private sector",type:"mix",impact:"Industry opposed in court."},{t:"Farmer protests Kurukshetra route block",type:"neg",impact:"Punjab farmers blocked. Police deployment."},{t:"Gurgaon-Manesar IT auto corridor expansion",type:"pos",impact:"Global auto hub. 5L+ jobs."}]},
 {name:"Goa",cm:"Pramod Sawant",party:"BJP",gdp:5.2,size:"0.95",hdi:0.761,lit:87.4,unemp:3.8,si:72,sw:68,se:78,sg:65,sn:55,decisions:[{t:"Coastal highway double lane completed",type:"pos",impact:"Tourism connectivity improved."},{t:"Casino expansion on rivers",type:"mix",impact:"Revenue increased. Social concerns."},{t:"Mhadei river water diversion fight",type:"neg",impact:"Conflict with Karnataka."}]},
 {name:"Tripura",cm:"Manik Saha",party:"BJP",gdp:5.0,size:"0.72",hdi:0.658,lit:87.2,unemp:5.5,si:60,sw:62,se:55,sg:62,sn:70,decisions:[{t:"Tripura-Bangladesh trade corridor Agartala",type:"pos",impact:"Agartala regional trade hub. Border trade tripled."},{t:"Rubber plantation economic diversification",type:"pos",impact:"Farmer income increasing."},{t:"Political violence post-2018 BJP win",type:"neg",impact:"CPI(M) offices attacked."}]},
 {name:"Chhattisgarh",cm:"Vishnu Deo Sai",party:"BJP",gdp:7.5,size:"4.2",hdi:0.613,lit:70.3,unemp:5.5,si:65,sw:68,se:68,sg:62,sn:62,decisions:[{t:"Naxal area Operation Kagar security",type:"mix",impact:"Commanders neutralised. Civilian casualties."},{t:"Mahtari Vandan Rs 1000/month 70L women",type:"pos",impact:"Delivered consistently."},{t:"Mining coal iron ore tribal displacement",type:"neg",impact:"Tribal displacement and livelihood loss ongoing."}]},
 {name:"Meghalaya",cm:"Conrad Sangma",party:"NPP",gdp:3.5,size:"0.39",hdi:0.656,lit:74.4,unemp:4.5,si:55,sw:60,se:52,sg:65,sn:78,decisions:[{t:"Coal mining ban environment compliance",type:"pos",impact:"Ecological damage reducing."},{t:"Meghalaya ecotourism green destination",type:"pos",impact:"International arrivals growing."}]},
 {name:"Mizoram",cm:"Lalduhoma",party:"ZPM",gdp:4.2,size:"0.31",hdi:0.705,lit:91.3,unemp:5.2,si:55,sw:65,se:50,sg:72,sn:78,decisions:[{t:"Myanmar refugee support 12000+ aided",type:"pos",impact:"Praised by UNHCR. Humanitarian leadership."},{t:"Drug trafficking border crackdown",type:"pos",impact:"Border enforcement improved."},{t:"ZPM democratic alternation first time",type:"pos",impact:"Broke duopoly. Democracy strengthened."}]},
 {name:"Nagaland",cm:"Neiphiu Rio",party:"NDPP",gdp:4.8,size:"0.37",hdi:0.679,lit:79.6,unemp:4.8,si:55,sw:62,se:52,sg:68,sn:75,decisions:[{t:"Naga peace talks decades-long",type:"mix",impact:"No final accord. Investor uncertainty."},{t:"Hornbill Festival cultural tourism",type:"pos",impact:"International visitors tripled."}]},
 {name:"Manipur",cm:"Y. Khemchand Singh",party:"BJP",gdp:4.0,size:"0.33",hdi:0.697,lit:76.9,unemp:6.2,si:52,sw:55,se:48,sg:40,sn:65,decisions:[{t:"Ethnic violence 2023 Meitei-Kuki conflict",type:"neg",impact:"200+ killed. 60000+ displaced. Economy collapsed."},{t:"Previous CM slow response Biren Singh",type:"neg",impact:"Delayed action cost lives."},{t:"Security operations AFSPA maintained",type:"mix",impact:"Insurgency controlled. Human rights concerns."}]},
 {name:"Sikkim",cm:"Prem Singh Tamang",party:"SKM",gdp:3.8,size:"0.43",hdi:0.716,lit:81.4,unemp:3.5,si:60,sw:70,se:65,sg:72,sn:85,decisions:[{t:"100% organic farming global pioneer",type:"pos",impact:"First fully organic state globally."},{t:"South Lhonak Lake GLO flood disaster 2023",type:"neg",impact:"100+ deaths. Rs 5000 crore damage."},{t:"Ecotourism development responsible model",type:"pos",impact:"International recognition."}]},
 {name:"Arunachal Pradesh",cm:"Pema Khandu",party:"BJP",gdp:4.5,size:"0.38",hdi:0.601,lit:65.4,unemp:4.5,si:58,sw:60,se:55,sg:65,sn:82,decisions:[{t:"Tawang standoff PLA incursion Dec 2022",type:"neg",impact:"Chinese troops entered. Sovereignty concerns."},{t:"Hydropower development India largest potential",type:"pos",impact:"50000 MW potential. Power for Northeast."},{t:"Vibrant Village Programme border retention",type:"pos",impact:"Infrastructure built. Population staying."}]},
 {name:"Jammu & Kashmir",cm:"Omar Abdullah",party:"NC",gdp:6.8,size:"2.2",hdi:0.688,lit:67.2,unemp:6.8,si:65,sw:65,se:60,sg:62,sn:78,decisions:[{t:"Restoration of democracy after 6 years",type:"pos",impact:"First elections post-Art 370. Record voter turnout."},{t:"Statehood demand Centre reluctance",type:"mix",impact:"J&K still UT. SC case ongoing."},{t:"Tourism boom 2 crore+ visitors in 2024",type:"pos",impact:"Record tourism. Economy improving."},{t:"Article 370 abrogation investment vs autonomy",type:"mix",impact:"Investment improved. Locals feel disenfranchised."}]},
 {name:"Puducherry",cm:"N. Rangaswamy",party:"AINRC",gdp:6.5,size:"0.30",hdi:0.738,lit:85.9,unemp:3.5,si:68,sw:65,se:72,sg:60,sn:60,decisions:[{t:"Statehood demand UT to state",type:"mix",impact:"Centre unresponsive."},{t:"Free sand scheme for construction",type:"pos",impact:"Housing construction boosted."},{t:"Tourism French heritage circuit",type:"pos",impact:"International visitors growing."}]}
];

/* ══ SEED ══════════════════════════════════════════ */
const insertPol = db.prepare(`INSERT OR REPLACE INTO politicians (name,role,state,party,twitter,initials,tab,term_start,term_end) VALUES (?,?,?,?,?,?,?,?,?)`);
const insertPromise = db.prepare(`INSERT INTO promises (politician_id,title,status,category) VALUES (?,?,?,?)`);
const insertParty = db.prepare(`INSERT OR REPLACE INTO parties (slug,name,full_name,color,founded,ideology,seats_2024,states_json) VALUES (?,?,?,?,?,?,?,?)`);
const insertManifest = db.prepare(`INSERT INTO manifesto_promises (party_id,term,year,title,status,impact) VALUES (?,?,?,?,?,?)`);
const insertState = db.prepare(`INSERT OR REPLACE INTO states (name,cm_name,party,gdp_growth,gdp_size,hdi,literacy,unemployment,score_infra,score_welfare,score_economy,score_govn,score_env) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`);
const insertDecision = db.prepare(`INSERT INTO state_decisions (state_id,title,type,impact) VALUES (?,?,?,?)`);

const seedAll = db.transaction(() => {
  // clear
  db.exec(`
    DELETE FROM promises;
    DELETE FROM politicians;
    DELETE FROM manifesto_promises;
    DELETE FROM parties;
    DELETE FROM state_decisions;
    DELETE FROM states;
    DELETE FROM sqlite_sequence
    WHERE name IN ('promises', 'politicians', 'manifesto_promises', 'parties', 'state_decisions', 'states');
  `);

  // politicians
  for (const [tab, pols] of Object.entries(POLITICIANS)) {
    for (const p of pols) {
      const res = insertPol.run(p.name, p.role, p.state, p.party, p.twitter, p.initials, tab, p.ts, p.te);
      for (const pr of p.promises) {
        insertPromise.run(res.lastInsertRowid, pr.t, pr.s, pr.c);
      }
    }
  }
  console.log(`✓ Politicians seeded`);

  // parties
  for (const par of PARTIES) {
    const res = insertParty.run(par.slug, par.name, par.full, par.color, par.founded, par.ideology, par.seats2024, par.states);
    for (const pr of par.prev.promises) insertManifest.run(res.lastInsertRowid,'prev',par.prev.year,pr.t,pr.s,pr.impact||'');
    for (const pr of par.curr.promises) insertManifest.run(res.lastInsertRowid,'curr',par.curr.year,pr.t,pr.s,pr.impact||'');
  }
  console.log(`✓ Parties seeded`);

  // states
  const statesRanked = [...STATES].sort((a,b)=>b.gdp-a.gdp).map((s,i)=>({...s,rank:i+1}));
  db.prepare(`UPDATE states SET rank_gdp=? WHERE name=?`); // after insert
  for (const s of statesRanked) {
    const res = insertState.run(s.name,s.cm,s.party,s.gdp,s.size,s.hdi,s.lit,s.unemp,s.si,s.sw,s.se,s.sg,s.sn);
    for (const d of s.decisions) insertDecision.run(res.lastInsertRowid,d.t,d.type,d.impact);
  }
  // rank by GDP
  const rankedIds = db.prepare(`SELECT id FROM states ORDER BY gdp_growth DESC`).all();
  for (let i=0;i<rankedIds.length;i++) db.prepare(`UPDATE states SET rank_gdp=? WHERE id=?`).run(i+1,rankedIds[i].id);
  console.log(`✓ States seeded`);
});

seedAll();
console.log('✅ Database seeded successfully!');
